import { motion } from "motion/react";

export function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-emerald-50 to-teal-50 py-20 lg:py-32">
        <div className="container mx-auto px-4 lg:px-8">
          <motion.div
            className="text-center max-w-3xl mx-auto space-y-6"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <motion.h1
              className="text-4xl lg:text-5xl xl:text-6xl"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2, duration: 0.8 }}
            >
              Privacy Policy
            </motion.h1>
            <motion.p
              className="text-lg text-foreground/70"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3, duration: 0.8 }}
            >
              Last updated: Oct 19, 2025
            </motion.p>
          </motion.div>
        </div>
      </section>

      {/* Content Section */}
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4 lg:px-8">
          <motion.div
            className="max-w-4xl mx-auto prose prose-lg"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4, duration: 0.8 }}
          >
            <div className="space-y-8">
              <div>
                <p className="text-foreground/70">
                  This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>
                <p className="text-foreground/70">
                  We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                </p>
              </div>

              <div>
                <h2>Interpretation and Definitions</h2>
                <h3>Interpretation</h3>
                <p className="text-foreground/70">
                  The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>
              </div>

              <div>
                <h3>Definitions</h3>
                <p className="text-foreground/70">For the purposes of this Privacy Policy:</p>
                <ul className="space-y-3 text-foreground/70">
                  <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                  <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                  <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Karuna Kodwani.</li>
                  <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                  <li><strong>Country</strong> refers to: Maharashtra, India</li>
                  <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                  <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                  <li><strong>Service</strong> refers to the Website.</li>
                  <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                  <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                  <li><strong>Website</strong> refers to Karuna Kodwani, accessible from https://www.karunakodwani.com</li>
                  <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
              </div>

              <div>
                <h2>Collecting and Using Your Personal Data</h2>
                <h3>Types of Data Collected</h3>
                <h4>Personal Data</h4>
                <p className="text-foreground/70">
                  While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                </p>
                <ul className="text-foreground/70">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Usage Data</li>
                </ul>
              </div>

              <div>
                <h3>Usage Data</h3>
                <p className="text-foreground/70">
                  Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
              </div>

              <div>
                <h3>Tracking Technologies and Cookies</h3>
                <p className="text-foreground/70">
                  We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. We use both Session and Persistent Cookies for the purposes set out below:
                </p>
                <ul className="space-y-3 text-foreground/70">
                  <li><strong>Necessary / Essential Cookies</strong> - These Cookies are essential to provide You with services available through the Website.</li>
                  <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> - These Cookies identify if users have accepted the use of cookies on the Website.</li>
                  <li><strong>Functionality Cookies</strong> - These Cookies allow us to remember choices You make when You use the Website.</li>
                </ul>
              </div>

              <div>
                <h2>Use of Your Personal Data</h2>
                <p className="text-foreground/70">The Company may use Personal Data for the following purposes:</p>
                <ul className="space-y-2 text-foreground/70">
                  <li>To provide and maintain our Service</li>
                  <li>To manage Your Account</li>
                  <li>For the performance of a contract</li>
                  <li>To contact You</li>
                  <li>To provide You with news, special offers and general information</li>
                  <li>To manage Your requests</li>
                  <li>For business transfers</li>
                  <li>For other purposes such as data analysis and service improvement</li>
                </ul>
              </div>

              <div>
                <h2>Retention of Your Personal Data</h2>
                <p className="text-foreground/70">
                  The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
                </p>
              </div>

              <div>
                <h2>Security of Your Personal Data</h2>
                <p className="text-foreground/70">
                  The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                </p>
              </div>

              <div>
                <h2>Children's Privacy</h2>
                <p className="text-foreground/70">
                  Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
                </p>
              </div>

              <div>
                <h2>Links to Other Websites</h2>
                <p className="text-foreground/70">
                  Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
                </p>
              </div>

              <div>
                <h2>Changes to this Privacy Policy</h2>
                <p className="text-foreground/70">
                  We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top of this Privacy Policy.
                </p>
              </div>

              <div className="bg-emerald-50 p-6 rounded-lg">
                <h3>Contact Us</h3>
                <p className="text-foreground/70">
                  If you have any questions about this Privacy Policy, You can contact us:
                </p>
                <p className="text-foreground/70">
                  By email: <a href="mailto:karunakodwani@gmail.com" className="text-emerald-600 hover:text-emerald-700">karunakodwani@gmail.com</a>
                </p>
              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
